---
- block:
    - include_tasks: context.yml

# FIXME
      
    - include_tasks: install.yml

    - include_tasks: setup.yml
      when: not runit_init

    - include_tasks: setup_as_init.yml
      when: runit_init

  when: want_runit

- name: set has_runit
  set_fact:
    has_runit: "{{ want_runit }}"
